### ISSUE TITLE
Support importing pattern from idenLib's database?

### ISSUE THREAD

**Issue by aaaddress1** [AirbusCyber/grap#2]
Hi, is that possible to import pattern from Project idenLib plugin? I think identifying known library functions is useful too.

https://github.com/secrary/idenLib

**Comment by yaps8** [comment]
Hello, this would be nice but I don't see how to convert pattern from idenLib.

According the readme these patterns are a list of hex values such as 89 89 7e d6 a0 88 b8 5d c3, but grap works on disassembled instructions, there is not easy way to convert this to an opcode list or anything else grap could use.

So this feels like two different approaches and I don't see an easy way to make them compatible.
